rm ./src/cmake-build-release/* -rf

cmake -S src -B src/cmake-build-release -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DUSE_FSAL_VFS=ON -DUSE_9P=OFF \
-DUSE_FSAL_LUSTRE=OFF -DUSE_FSAL_GPFS=OFF \
-DUSE_NLM=OFF -DUSE_FSAL_CEPH:STRING=OFF \
-DUSE_FSAL_GLUSTER:STRING=OFF -DUSE_FSAL_KVSFS:STRING=OFF \
-DUSE_FSAL_LIZARDFS:STRING=OFF -DUSE_FSAL_NULL:STRING=OFF \
-DUSE_FSAL_MEM:STRING=OFF -DUSE_FSAL_PROXY_V3:STRING=OFF \
-DUSE_FSAL_PROXY_V4:STRING=OFF -DUSE_FSAL_RGW:STRING=OFF \
-DUSE_FSAL_XFS:STRING=OFF -DUSE_GSS=OFF

cmake --build src/cmake-build-release --parallel 20
